apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: public.ecr.aws/c9e0d4u8/httpd:2.4
        ports:
        - containerPort: 80
       
---
kind: Service
apiVersion: v1
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
   
kind: Ingress
   
metadata:
   
  name: httpd-ingress
   
  annotations:
   
    nginx.ingress.kubernetes.io/rewrite-target: /
   
spec:
   
  rules:
   
      http:
   
        paths:
   
          - path: /
   
            pathType: Prefix
   
            backend:
   
              service:
   
                name: httpd-Service
   
                port:
   
                  number: 80


